import {
	afterAll,
	afterEach,
	beforeAll,
	describe,
	expect,
	test,
} from "bun:test";
import type { SQL } from "bun";
import { mkdir, rm } from "fs/promises";
import { tmpdir } from "os";
import { join } from "path";

import { generateSchema } from "../src/introspect";
import type { ResolvedConfig } from "../src/types";
import { getTestConnection, resetDatabase } from "./helpers/postgres";

let connection: SQL;
let tempDir: string;

beforeAll(() => {
	connection = getTestConnection();
});

afterAll(async () => {
	await connection.close();
});

afterEach(async () => {
	await resetDatabase(connection);
	if (tempDir) {
		await rm(tempDir, { recursive: true, force: true });
	}
});

function makeConfig(): ResolvedConfig {
	tempDir = join(tmpdir(), `baked-introspect-${Date.now()}`);
	return {
		migrationsPath: join(tempDir, "migrations"),
		schemaPath: join(tempDir, "schema.ts"),
		modelsPath: "./models",
		frontendModelsPath: "./frontend/models",
	};
}

describe("generateSchema", () => {
	test("generates schema file with table definitions", async () => {
		await connection`
			CREATE TABLE users (
				id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
				name text NOT NULL,
				email text NOT NULL,
				created_at timestamptz NOT NULL DEFAULT now()
			)
		`;

		const config = makeConfig();
		await mkdir(tempDir, { recursive: true });
		await generateSchema(connection, config, "20240101000000");

		const content = await Bun.file(config.schemaPath).text();

		expect(content).toContain("Auto-generated by baked-orm");
		expect(content).toContain("class UsersRow");
		expect(content).toContain("declare id: string");
		expect(content).toContain("declare name: string");
		expect(content).toContain("declare email: string");
		expect(content).toContain("declare createdAt: Date");
		expect(content).toContain('version: "20240101000000"');
		expect(content).toContain("tables: { users }");
	});

	test("includes primary keys and foreign keys", async () => {
		await connection`
			CREATE TABLE users (
				id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
				name text NOT NULL
			)
		`;
		await connection`
			CREATE TABLE posts (
				id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
				user_id uuid NOT NULL REFERENCES users(id),
				title text NOT NULL
			)
		`;

		const config = makeConfig();
		await mkdir(tempDir, { recursive: true });
		await generateSchema(connection, config, "20240101000001");

		const content = await Bun.file(config.schemaPath).text();

		expect(content).toContain("class UsersRow");
		expect(content).toContain("class PostsRow");
		expect(content).toContain('primaryKey: ["id"]');
		expect(content).toContain("foreignKeys:");
		expect(content).toContain('"users"');
	});

	test("includes indexes", async () => {
		await connection`
			CREATE TABLE users (
				id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
				email text NOT NULL
			)
		`;
		await connection`CREATE UNIQUE INDEX idx_users_email ON users (email)`;

		const config = makeConfig();
		await mkdir(tempDir, { recursive: true });
		await generateSchema(connection, config, "20240101000000");

		const content = await Bun.file(config.schemaPath).text();

		expect(content).toContain("idx_users_email");
		expect(content).toContain("unique: true");
	});

	test("handles nullable columns", async () => {
		await connection`
			CREATE TABLE profiles (
				id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
				bio text,
				avatar_url text
			)
		`;

		const config = makeConfig();
		await mkdir(tempDir, { recursive: true });
		await generateSchema(connection, config, "20240101000000");

		const content = await Bun.file(config.schemaPath).text();

		expect(content).toContain("declare bio: string | null");
		expect(content).toContain("declare avatarUrl: string | null");
	});

	test("excludes schema_migrations table", async () => {
		await connection`
			CREATE TABLE schema_migrations (version VARCHAR(255) NOT NULL PRIMARY KEY)
		`;
		await connection`
			CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid())
		`;

		const config = makeConfig();
		await mkdir(tempDir, { recursive: true });
		await generateSchema(connection, config, "20240101000000");

		const content = await Bun.file(config.schemaPath).text();

		expect(content).toContain("class UsersRow");
		expect(content).not.toContain("SchemaMigrationsRow");
	});

	test("generates empty schema for empty database", async () => {
		const config = makeConfig();
		await mkdir(tempDir, { recursive: true });
		await generateSchema(connection, config, undefined);

		const content = await Bun.file(config.schemaPath).text();

		expect(content).toContain("Auto-generated by baked-orm");
		expect(content).toContain('version: "none"');
		expect(content).toContain("tables: {  }");
	});

	test("handles enum types", async () => {
		await connection`CREATE TYPE status AS ENUM ('active', 'inactive', 'archived')`;
		await connection`
			CREATE TABLE users (
				id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
				name text NOT NULL,
				status status NOT NULL DEFAULT 'active'
			)
		`;

		const config = makeConfig();
		await mkdir(tempDir, { recursive: true });
		await generateSchema(connection, config, "20240101000000");

		const content = await Bun.file(config.schemaPath).text();

		// Enum type definition
		expect(content).toContain(
			'export type Status = "active" | "inactive" | "archived";',
		);
		expect(content).toContain(
			'export const StatusValues = ["active", "inactive", "archived"] as const;',
		);

		// Row class uses enum type
		expect(content).toContain("declare status: Status");

		// Column definition includes enumValues
		expect(content).toContain("enumValues: StatusValues");
	});

	test("handles multiple enum types", async () => {
		await connection`CREATE TYPE status AS ENUM ('active', 'inactive')`;
		await connection`CREATE TYPE user_role AS ENUM ('admin', 'user', 'moderator')`;
		await connection`
			CREATE TABLE users (
				id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
				status status NOT NULL,
				role user_role NOT NULL
			)
		`;

		const config = makeConfig();
		await mkdir(tempDir, { recursive: true });
		await generateSchema(connection, config, "20240101000000");

		const content = await Bun.file(config.schemaPath).text();

		expect(content).toContain('export type Status = "active" | "inactive";');
		expect(content).toContain(
			'export type UserRole = "admin" | "user" | "moderator";',
		);
		expect(content).toContain("declare status: Status");
		expect(content).toContain("declare role: UserRole");
	});

	test("handles nullable enum columns", async () => {
		await connection`CREATE TYPE status AS ENUM ('active', 'inactive')`;
		await connection`
			CREATE TABLE users (
				id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
				status status
			)
		`;

		const config = makeConfig();
		await mkdir(tempDir, { recursive: true });
		await generateSchema(connection, config, "20240101000000");

		const content = await Bun.file(config.schemaPath).text();

		expect(content).toContain("declare status: Status | null");
	});

	test("handles composite types", async () => {
		await connection`CREATE TYPE address AS (street text, city text, zip text)`;
		await connection`
			CREATE TABLE contacts (
				id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
				home_address address
			)
		`;

		const config = makeConfig();
		await mkdir(tempDir, { recursive: true });
		await generateSchema(connection, config, "20240101000000");

		const content = await Bun.file(config.schemaPath).text();

		expect(content).toContain("class AddressComposite");
		expect(content).toContain("declare street: string");
		expect(content).toContain("declare city: string");
		expect(content).toContain("declare zip: string");

		// Row class uses composite type
		expect(content).toContain("declare homeAddress: AddressComposite | null");
	});

	test("handles enum and composite types in the same schema", async () => {
		await connection`CREATE TYPE status AS ENUM ('active', 'inactive')`;
		await connection`CREATE TYPE address AS (street text, city text)`;
		await connection`
			CREATE TABLE users (
				id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
				status status NOT NULL,
				home_address address
			)
		`;

		const config = makeConfig();
		await mkdir(tempDir, { recursive: true });
		await generateSchema(connection, config, "20240101000000");

		const content = await Bun.file(config.schemaPath).text();

		// Enum section
		expect(content).toContain('export type Status = "active" | "inactive"');
		expect(content).toContain("export const StatusValues =");

		// Composite section
		expect(content).toContain("class AddressComposite");

		// Row class uses both
		expect(content).toContain("declare status: Status");
		expect(content).toContain("declare homeAddress: AddressComposite | null");

		// Enum column has enumValues, composite column does not
		expect(content).toContain("enumValues: StatusValues");
	});
});
