import { QueryBuilder } from "../model/query";
import type { AnyModelStatic } from "../model/types";

/** @internal */
// biome-ignore lint/suspicious/noExplicitAny: plugin methods are generic across all model types
type AnyFunction = (...args: any[]) => any;

/**
 * A plugin-contributed virtual attribute. The `get` function is called when
 * the virtual is read or serialized. Provide `set` to make the virtual settable
 * via `instance.name = value`; without it, assignment throws in strict mode
 * (JS handles this naturally via getter-only accessor descriptors).
 */
export type PluginVirtual = {
	get: (instance: unknown) => unknown;
	set?: (instance: unknown, value: unknown) => void;
};

/**
 * Definition for a baked-orm plugin. Plugins add methods to model instances,
 * model classes (statics), and/or the QueryBuilder prototype, and may
 * contribute virtual attributes that auto-serialize through `toJSON()`.
 *
 * Built-in plugins (soft-delete, locking, recursive-cte, batch-iteration,
 * aggregates) use this exact same API — see `src/plugins/` for canonical examples.
 */
export interface ModelPlugin {
	name: string;
	/** Instance methods/getters added to every model class prototype (NOT serialized). */
	instance?: Record<string, AnyFunction | PropertyDescriptor>;
	/** Static methods added to every model class. */
	static?: Record<string, AnyFunction | PropertyDescriptor>;
	/** Methods added to QueryBuilder.prototype (applied once at registration time). */
	queryBuilder?: Record<string, AnyFunction | PropertyDescriptor>;
	/**
	 * Contribute virtual attributes per model. Called once per model class
	 * inside `applyModelPlugins`. Return an empty object to skip a given model
	 * (useful for plugins that gate on per-model statics like `static auditFields = true`).
	 *
	 * Plugin authors are responsible for type-side declarations via
	 * `declare module "../model/types" { interface BaseModel { ... } }` —
	 * see the README for the pattern.
	 */
	virtuals?: (modelClass: AnyModelStatic) => Record<string, PluginVirtual>;
}

const registeredPlugins: ModelPlugin[] = [];

/** Per-model registry of plugin-contributed virtual names, populated at applyModelPlugins time. */
const pluginVirtualsRegistry = new WeakMap<object, Set<string>>();

/** @internal — used by `getComputedVirtuals` to union plugin names with user-declared getters. */
export function getPluginVirtuals(modelClass: object): Set<string> {
	return pluginVirtualsRegistry.get(modelClass) ?? new Set();
}

function applyProperties(
	target: object,
	properties: Record<string, AnyFunction | PropertyDescriptor>,
): void {
	for (const [name, value] of Object.entries(properties)) {
		if (typeof value === "function") {
			Object.defineProperty(target, name, {
				value,
				writable: true,
				configurable: true,
				enumerable: false,
			});
		} else if (isPropertyDescriptor(value)) {
			Object.defineProperty(target, name, value);
		} else {
			throw new Error(
				`Plugin property "${name}" is neither a function nor a PropertyDescriptor`,
			);
		}
	}
}

function isPropertyDescriptor(value: unknown): value is PropertyDescriptor {
	if (typeof value !== "object" || value === null) return false;
	const descriptor = value as Record<string, unknown>;
	return "get" in descriptor || "set" in descriptor || "value" in descriptor;
}

/**
 * Register a plugin. QueryBuilder methods are patched immediately.
 * Model instance/static methods are stored and applied per-model by
 * `applyModelPlugins()`, which is called inside the `Model()` factory.
 *
 * Call `definePlugin()` at module top-level so plugins are registered
 * before any models are created.
 */
export function definePlugin(plugin: ModelPlugin): void {
	registeredPlugins.push(plugin);

	if (plugin.queryBuilder) {
		applyProperties(QueryBuilder.prototype, plugin.queryBuilder);
	}
}

/**
 * Apply all registered plugin instance/static methods to a model class.
 * Called internally by the `Model()` factory for each new model class.
 * @internal
 */
export function applyModelPlugins(modelClass: {
	// biome-ignore lint/suspicious/noExplicitAny: model classes are generic
	prototype: any;
}): void {
	for (const plugin of registeredPlugins) {
		if (plugin.instance) {
			applyProperties(modelClass.prototype, plugin.instance);
		}
		if (plugin.static) {
			applyProperties(modelClass, plugin.static);
		}
	}
	// Plugin `virtuals` are NOT collected here — `applyModelPlugins` is called on
	// the inner ModelBase class generated by the `Model()` factory, before the
	// user's subclass (with its gating statics) exists. Collection is deferred
	// to `ensurePluginVirtuals`, called from the ModelBase constructor on the
	// first instance of each concrete subclass.
}

/**
 * Lazily collect plugin-contributed virtuals for the user's concrete subclass.
 * Idempotent: subsequent calls for the same class are a no-op. Called from the
 * ModelBase constructor on every instance creation (the WeakMap.has fast-path
 * keeps repeated construction cheap).
 *
 * @internal
 */
export function ensurePluginVirtuals(modelClass: AnyModelStatic): void {
	if (pluginVirtualsRegistry.has(modelClass)) return;
	const names = collectPluginVirtuals(modelClass);
	pluginVirtualsRegistry.set(modelClass, names);
}

function collectPluginVirtuals(modelClass: AnyModelStatic): Set<string> {
	const columns = modelClass.tableDefinition?.columns ?? {};
	const seen = new Map<string, string>();
	const names = new Set<string>();

	const prototype = (modelClass as unknown as { prototype: object }).prototype;
	// Snapshot user-declared prototype property names BEFORE plugin iteration so
	// later plugins don't mistake an earlier plugin's accessor for a user member.
	const userDeclared = new Set(Object.getOwnPropertyNames(prototype));

	for (const plugin of registeredPlugins) {
		if (!plugin.virtuals) continue;
		const contributions = plugin.virtuals(modelClass);
		for (const [name, contribution] of Object.entries(contributions)) {
			if (name in columns) continue;
			if (isAssociationName(modelClass, name)) continue;
			// User-declared property on the subclass prototype (getter, setter, or
			// method) wins silently — the user shouldn't have to know what plugins
			// are loaded to name their own members.
			if (userDeclared.has(name)) continue;
			const existing = seen.get(name);
			if (existing !== undefined) {
				throw new Error(
					`Plugin "${plugin.name}" tried to contribute virtual "${name}" on ${modelClass.name}, but plugin "${existing}" already registered it. Each plugin virtual name must be unique per model.`,
				);
			}
			seen.set(name, plugin.name);
			defineVirtualAccessor(prototype, name, contribution);
			names.add(name);
		}
	}

	return names;
}

function defineVirtualAccessor(
	prototype: object,
	name: string,
	{ get, set }: PluginVirtual,
): void {
	const descriptor: PropertyDescriptor = {
		get(this: unknown) {
			return get(this);
		},
		enumerable: false,
		configurable: true,
	};
	if (set) {
		descriptor.set = function (this: unknown, value: unknown) {
			set(this, value);
		};
	}
	Object.defineProperty(prototype, name, descriptor);
}

function isAssociationName(modelClass: AnyModelStatic, name: string): boolean {
	const value = (modelClass as unknown as Record<string, unknown>)[name];
	return (
		typeof value === "object" &&
		value !== null &&
		"associationType" in (value as Record<string, unknown>)
	);
}
